@Commit.Api_HostAddress = http://localhost:5197

POST http://localhost:5197/api/auth/register
Content-Type: application/json
{
  "email": "test123@gmail.com",
  "password": "Test1234@",
  "displayName": ""
}
###

POST http://localhost:5197/api/auth/login
Content-Type: application/json
{
  "email": "test123@gmail.com",
  "password": "Test1234@"
}

###
POST http://localhost:5197/api/auth/refresh-token
Content-Type: application/json
{
  "refreshToken": "PASTE_YOUR_OWN_TOKEN_HERE"
}